### ISSUE TITLE
M4 should be able to access the Edge TPU

### ISSUE THREAD

**Issue by ra-bool** [google-coral/coralmicro#13]
### Description

It would be a great help for us if we could access TPU using M4 core on Coral Dev Board Micro. M4 core currently cannot access the USB stack.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Operating System

Mac OS

### Programming Language

C++

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hi @ra-bool  Unfortunately, we don't have any plans to make M4 to access the Edge TPU. Thanks!
