### ISSUE TITLE
Coral site doesn't link to the correct examples folder here

### ISSUE THREAD

**Issue by eggheaded** [google-coral/coralmicro#20]
### Description

While the [site ](https://coral.ai/examples/#code-examples) now notes that their examples aren't compatible with the Dev Board Micro it points to the wrong url. Should be: https://github.com/google-coral/coralmicro/tree/main/examples over [this.](https://github.com/google-coral/coralmicro/examples/)

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hello @eggheaded the link got updated. Thanks for reporting.
