### ISSUE TITLE
Coral Micro examples on the Arduino Legacy IDE (1.8.X) 

### ISSUE THREAD

**Issue by hpssjellis** [google-coral/coralmicro#22]
### Description

Is there any plan to allow the Coral-micro examples to be used on the older [Legacy IDE (1.8.X)](https://www.arduino.cc/en/software) ?

As the new Arduino IDE 2.x had some hiccups when it was first introduced, some educational facilities were slow to update to the new IDE, is there a plan to allow Coral Micro to load the examples for the old IDE?

P.S. The board installs fine on the old IDE, I have not tested it as I don't have a Coral-micro yet.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Operating System

Windows 10, Ubuntu

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Unfortunately, No. We don't have any plans to support old IDE. https://coral.ai/docs/dev-board-micro/arduino/#1-gather-requirements

![image](https://user-images.githubusercontent.com/86132058/218520968-7ea8543d-4553-451f-a0cb-01e0b35ce898.png)

**Comment by hpssjellis** [comment]
Thanks @hjonnala for the reply. I can close this issue. I have a few other questions but will put them in their own issues.
