### ISSUE TITLE
Arduino support for the M4 core?

### ISSUE THREAD

**Issue by hpssjellis** [google-coral/coralmicro#23]
### Description

Does Coral plan to allow Arduino compiling for the M4 core, like the Arduino PortentaH7 can choose either the M7 or M4 cores from the boards menu?
![image](https://user-images.githubusercontent.com/5605614/218527626-4d127a4f-463b-4da2-820a-72380c3b2bf5.png)

I have seen the documentation that allows cMake compiling of the M4 core [here](https://coral.ai/docs/dev-board-micro/multicore/#define-an-m4-program-with-cmake).

If not @hjonnala you can close this issue.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

_No response_

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
No, The available options are:
1. Tools > Board > Coral > Dev Board Micro
2. Tools > Board > Coral > Dev Board Micro + PoE Add-on 
3. Tools > Board > Coral > Dev Board Micro + Wireless Add-on
