### ISSUE TITLE
Camera images have color flare

### ISSUE THREAD

**Issue by metanav** [google-coral/coralmicro#28]
I am running the default **multicore_model_cascade** example  app on the Coral micro dev board (just received it yesterday) and streaming the images over USB on a Linux Virtualbox (macOS host).

```
$ python3 scripts/flashtool.py -a multicore_model_cascade

$ python3 apps/multicore_model_cascade/multicore_model_cascade.py

```
The person/pose detection works but the images have always some kind of round color flare/overlay (like a rainbow)  as you can see in the screenshot below.

<img width="544" alt="Screenshot 2023-03-17 at 7 09 18" src="https://user-images.githubusercontent.com/7456984/225765232-b559dbe4-9f18-4704-833e-87b640668d51.png">

<img width="475" alt="Screenshot 2023-03-17 at 7 42 06" src="https://user-images.githubusercontent.com/7456984/225769084-eaf4d797-59bb-4f80-995f-bbbb67e545c6.png">

Is it normal or my micro dev camera have any lens/sensor defects? Since I plan to use the RGB images for a custom model and my use case depends on the color of the objects so please confirm it.

PS: I have already removed the protection sticker on the lens.

**Comment by hjonnala** [comment]
> Is it normal or my micro dev camera have any lens/sensor defects? Since I plan to use the RGB images for a custom model and my use case depends on the color of the objects so please confirm it.

yes, it is normal.

**Comment by hjonnala** [comment]
I think, it depends on camera angle and exposure to the light. Please try placing dev board micro in different positions.

**Comment by metanav** [comment]
I have tried all angles and positions in different lighting conditions (day/night, indoor/outdoor) but the image always have spots.

**Comment by josecols** [comment]
I noticed that part of the color flare is caused by the camera and TPU LEDs, which is especially true if you use the case. A workaround that helped me is reducing the brightness of the TPU LED with `LedSetBrightness(Led::kTpu, 1);`. But unfortunately, the API does not exposes the camera LED.

Another option is using the [DiscardFrames function](https://coral.ai/docs/reference/micro/camera/#_CPPv4N10coralmicro10CameraTask13DiscardFramesEi) to auto-calibrate the sensor.

**Comment by metanav** [comment]
I tried to cover the camera LED and TPU LED by  a black tape which seems not helpful. I will try to use the [DiscardFrames function](https://coral.ai/docs/reference/micro/camera/#_CPPv4N10coralmicro10CameraTask13DiscardFramesEi) later. By the way, do you see the similar color flares or less as I have on the images in the previous posts?

**Comment by metanav** [comment]
I have tried the suggestions but they did not fix the issue. I believe the camera has issues.

**Comment by hjonnala** [comment]
Hi @metanav unfortunately, color flares are expected with the on board camera. Please test your custom model on dev board micro. If the performance is not as expected, please try  [Dev Board](https://coral.ai/products/dev-board) with a USB camera or if possible, please design a custom board with the [accelerator-module](https://coral.ai/products/accelerator-module) as per your requirements.

Thanks!!
