### ISSUE TITLE
1.8V tolerant pins

### ISSUE THREAD

**Issue by metanav** [google-coral/coralmicro#31]
I wanted to connect a few I2C sensors (logic voltage 3.3V) to the Coral Dev Board Micro. It seems all the pins are 1.8V tolerant except TX/RX pins. I have used the TX/RX to interface another dev board in one of my community projects (see the link below) but it is a burden to power up them and maintain separate code base.

https://www.hackster.io/naveenbskumar/fart-monitoring-using-coral-dev-board-micro-d3333a
 
What is the reason to have 1.8V tolerant pins? I guess I would need a logic level shifter to connect the sensors.

**Comment by hjonnala** [comment]
> What is the reason to have 1.8V tolerant pins? I guess I would need a logic level shifter to connect the sensors.

Yes, you will need a level shifter if the sensor only supports down to 3.3V since the RT1176 IO voltage is powered with 1.8V on the Coral Dev Board Micro.
