### ISSUE TITLE
Issue accessing Jtag on Coral Micro Dev Board

### ISSUE THREAD

**Issue by Tarek-Mhareb** [google-coral/coralmicro#33]
### Description

Hello,

We are unable to connect using JTAG on the board.
The pictures shows the simple setup but the connection fails every time.
We tried Keil debuggers and we are still unable to communicate with the board.
Do we have to use an external power supply and free the USB port?

Thanks

![Coral Debugg1](https://user-images.githubusercontent.com/90411881/226616217-21584b35-f96f-43ce-bf85-5bee0a0c6c6e.jpg)
![Coral Debugg](https://user-images.githubusercontent.com/90411881/226616310-2d575be6-1099-4098-a8d2-a575be9a5710.JPG)
![Coral Debugg2](https://user-images.githubusercontent.com/90411881/226616344-bf5e5fac-cbc3-4d1e-9709-c295775fa0e5.JPG)
![Coral Debugg3](https://user-images.githubusercontent.com/90411881/226616372-eea70a5e-8880-404d-9fdc-f0df2348765b.JPG)
![Coral Debugg4](https://user-images.githubusercontent.com/90411881/226616401-7a51bcf8-50b8-4e06-a4e3-00f893736caf.JPG)

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Operating System

Windows 10, Ubuntu

### Coral Device

Dev Board Micro

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hi @Tarek-Mhareb can you please try the set up software section mentioned at: https://coral.ai/docs/dev-board-micro/wireless-addon/#jtag

**Comment by hjonnala** [comment]
Hi @Tarek-Mhareb were you able to access the jtag?

**Comment by Tarek-Mhareb** [comment]
Hello @hjonnala 

I am using Linux Ubuntu and SWD (Jtag) now.
I am getting the following error every time I try to connect.
[Jlink CMD Log](https://github.com/google-coral/coralmicro/files/11101650/Jlink.CMD.Log)
Here how it should be
[NXP EVK Board.txt](https://github.com/google-coral/coralmicro/files/11101799/NXP.EVK.Board.txt)
I tried both serial and default modes.
Thanks,
Tarek

**Comment by hjonnala** [comment]
Looks like you would need a wireless add on board or custom add on board as per [requirements](https://coral.ai/docs/dev-board-micro/wireless-addon/#requirements). 

Can you pls try attaching wireless add on board: https://www.mouser.com/ProductDetail/Coral/G650-07974-01?qs=vvQtp7zwQdMFLSVsQtkh5g%3D%3D

**Comment by Tarek-Mhareb** [comment]
Hi @hjonnala 
I forgot to mention that it is attached on a custom board. It is not possible to connect to all jtag pins from interface.
![Coral Jtag](https://user-images.githubusercontent.com/90411881/228631483-96045d32-18cc-44e5-b0e4-d73b54209e8c.jpg)

**Comment by hjonnala** [comment]
Does the custom board has  board to board connectors? https://coral.ai/docs/dev-board-micro/get-started/#2-get-to-know-the-board. I don't think, it would work without those connections.

**Comment by Tarek-Mhareb** [comment]
There are of course board to board connectors.
I attached a picture to show you exactly that the board is attached to a custom prototype carrier board with jtag connector showed in the picture.
Can you verify that the serial mode is the correct mode for jtag connection and that we can use jtag to flash to NXP’s on board?
Thanks

**Comment by Tarek-Mhareb** [comment]
Hi,
I also attached here the command line steps with the error.

![jtag _from_cmd](https://user-images.githubusercontent.com/90411881/229198391-ef87d2ae-5963-4343-8c41-a804dab89b46.png)

**Comment by hjonnala** [comment]
Hi, It looks like you are trying to debug without all the JTAG pins, since they are only connecting to the headers and not all the JTAG pins are broken out there. Unfortunately, this isn't supported.

Here are the some recommendation for you:

1. You can buy the wifi board and use that for debug. This is the only officially supported JTAG debugging method. 

2. or you can use [altium design files](https://github.com/google-coral/electricals/tree/master/dev_board_micro) to locate the Dev Board Micro pads with the remaining JTAG signals and solder their own wires to the PCB to connect to their debugger. 

3. or you can design another board that does break out the all JTAG pins available on the WIFI board from the high density connectors.

Thanks!

**Comment by Tarek-Mhareb** [comment]
Hello,

The header was first used without the add-on board. The add-on board has the full jtag as shown.
The error obtained from Jlink commander seems to show that the communication was established so it might not be a hardware issue. 
Thank you
![b2b2](https://user-images.githubusercontent.com/90411881/229804733-b4a320a6-98db-4544-9efc-9f16ea4a28fb.JPG)
![b2b3](https://user-images.githubusercontent.com/90411881/229804739-d892f5cd-f199-4f19-b4bf-d5eec3db8e09.JPG)
![InkedCoral Jtag](https://user-images.githubusercontent.com/90411881/229804741-60e8ac02-4eef-4cee-b7a2-87e5d17ccb1f.jpg)
![JTAG](https://user-images.githubusercontent.com/90411881/229804771-a8feb841-d046-4d94-ac3c-6a88e3ccf109.JPG)
![PCB](https://user-images.githubusercontent.com/90411881/229804778-41db2767-4dae-48a2-bc4f-2f0693801fe1.JPG)
![b2b1](https://user-images.githubusercontent.com/90411881/229804784-652017a1-934b-46fa-a5a0-d4fbe2a50ecc.JPG)

**Comment by hjonnala** [comment]
> I am using Linux Ubuntu and SWD (Jtag) now. I am getting the following error every time I try to connect. [Jlink CMD Log](https://github.com/google-coral/coralmicro/files/11101650/Jlink.CMD.Log) Here how it should be [NXP EVK Board.txt](https://github.com/google-coral/coralmicro/files/11101799/NXP.EVK.Board.txt) 

Please check with the NXP community if they have any suugestions for the Jlink CMD Log issue: https://community.nxp.com/t5/i-MX-RT/Failed-to-power-up-DAP-ERROR-Could-not-connect-to-target/m-p/1503062#M20946




> ![jtag _from_cmd](https://user-images.githubusercontent.com/90411881/229198391-ef87d2ae-5963-4343-8c41-a804dab89b46.png)

To debug the blink_led error first try to flash the blink_led and then try with --debug flag: https://coral.ai/docs/dev-board-micro/wireless-addon/#flash-for-debugging
To revise the GDB commands that run our app, open scripts/flashtool.py and edit the StateStartGdb function: https://github.com/google-coral/coralmicro/blob/main/scripts/flashtool.py#L789

**Comment by Tarek-Mhareb** [comment]
Hello @hjonnala ,

I was able after several tries to use JTAG. I can use both modes, but it seems that the USB has to be also connected in serial mode. JTAG can also be verified using windows/Linux JTAG Commander.
You can mark this as solved but I have a question related to flashing bare metal projects.
I used Mcuxpresso with JTAG and I was able to debug but not flash. I linked the application to RAM and performed real time debugging. I was not able to flash to QSPI memory onboard because it seems that the memory starting address is not at 0x30000000. Could you please provide us with the correct configuration for flashing C projects?

Thank you

**Comment by hjonnala** [comment]
> I was able after several tries to use JTAG. I can use both modes, but it seems that the USB has to be also connected in serial mode. JTAG can also be verified using windows/Linux JTAG Commander.

Great, Thanks for letting us know.

> I used Mcuxpresso with JTAG and I was able to debug but not flash. I linked the application to RAM and performed real time debugging. I was not able to flash to QSPI memory onboard because it seems that the memory starting address is not at 0x30000000. Could you please provide us with the correct configuration for flashing C projects?

Unfortunately, I don't have experience with Mcuxpresso IDE. Please use the setps mentioned for [FreeRTOS](https://coral.ai/docs/dev-board-micro/freertos/) or [arduino IDE](https://coral.ai/docs/dev-board-micro/arduino/) to flash the Dev Board Micro. Thanks!!

**Comment by wawanUnic** [comment]
@Tarek-Mhareb,
Hello. Tell me, will the following programmers be suitable for this microcontroller iMXRT1176?

1. https://www.waveshare.com/st-link-v2-mini-stm32.htm
2. https://www.waveshare.com/st-link-v2-mini-stm32.htm

Will they be able to program it? Will it be possible to debug it?
