### ISSUE TITLE
setup.sh fails with: Failed to send reload request: No such file or directory + solution

### ISSUE THREAD

**Issue by paloj** [google-coral/coralmicro#36]
### Description

Following the getting started tutorial and after 'bash setup.sh' and getting "Failed to send reload request: No such file or directory".
This was under Windows 11 WSL:
OS: Ubuntu 20.04.6 LTS on Windows 10 x86_64
Kernel: 5.10.102.1-microsoft-standard-WSL2

The solution was to run: sudo service udev restart
After that the part "sudo udevadm control --reload-rules" on the setup.sh script worked and the setup was run succesfully.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Operating System

Linux, Ubuntu

### Coral Device

Dev Board Micro

### Programming Language

Other

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
@paloj  Thanks for reporting the probelm as well as solution.
