### ISSUE TITLE
 We need more kindness about examples 

### ISSUE THREAD

**Issue by cugfk** [google-coral/coralmicro#39]
### Description

Thank you for making good examples but we need more kind explanations.
https://github.com/google-coral/coralmicro/tree/main/examples
That's not easy for beginner how to use and install.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

_No response_

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hi @cugfk could you please follow the documentation on below links, and let me know if you have any issue in trying out any particular example. Thanks..

- https://coral.ai/docs/dev-board-micro/get-started/
- https://github.com/google-coral/coralmicro#get-the-code

**Comment by cugfk** [comment]
I need how to start and use more kind texts & pictures for  https://github.com/google-coral/coralmicro/tree/main/examples .

**Comment by hjonnala** [comment]
Unforutanely, its not possible due to the other proriorites. Any contributions from communtiy are welcome and greatly appreciated.. Thanks!!
