### ISSUE TITLE
Coral Micro Inference Times Significantly Longer Than USB Stick 

### ISSUE THREAD

**Issue by drummerhul** [google-coral/coralmicro#40]
### Description

We've been doing some quick and dirty profiling of the stock object detection models on the coral.ai [website](https://coral.ai/models/object-detection/) using `TimerMillis()`. In particular, we've noticed the [SSD MobileNet V2](https://raw.githubusercontent.com/google-coral/test_data/master/tf2_ssd_mobilenet_v2_coco17_ptq_edgetpu.tflite) runs around 83 ms. In previous testing, [Mobile Net V2](
https://github.com/google-coral/edgetpu/raw/master/test_data/ssd_mobilenet_v2_coco_quant_postprocess_edgetpu.tflite) running on the USB Accelerator connected to a RPI4b through its USB3 running Python the inference times in the 23 ms range. 

The benchmark on the model page shows 7.6 ms. 

Our expectation was to get close to the same performance (or slightly degraded) as on other host platforms. Though not a 4x difference. 

Is this level of performance degradation on the Coral Micro expected? If so, why?

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Operating System

Ubuntu

### Coral Device

USB Accelerator, Dev Board Micro

### Other Devices

Rapsberry Pi 4

### Programming Language

C++, Python 3.9

### Relevant Log Output

```shell
Here's some sample `printf` output on the Coral Micro:

Inference time : 324 ms 
Inference time : 83 ms 
Inference time : 84 ms 
Inference time : 84 ms 
Inference time : 83 ms 
Inference time : 84 ms 
Inference time : 84 ms 
Inference time : 83 ms 
Inference time : 83 ms 
Inference time : 84 ms 
Inference time : 84 ms 
Inference time : 84 ms 
Inference time : 84 ms 
Inference time : 84 ms 
Inference time : 84 ms 
Inference time : 83 ms 
Inference time : 84 ms 
Inference time : 84 ms 
Inference time : 84 ms 
Inference time : 84 ms 
Inference time : 84 ms 
Inference time : 83 ms 
Inference time : 83 ms 
Inference time : 84 ms 
Inference time : 83 ms 
Inference time : 83 ms 
Inference time : 84 ms 
Inference time : 83 ms 
Inference time : 84 ms 
Inference time : 83 ms 
Inference time : 84 ms 
Inference time : 84 ms 
Inference time : 84 ms 
Inference time : 84 ms 
Inference time : 83 ms 
Inference time : 83 ms 
Inference time : 84 ms 
Inference time : 83 ms
```
</details>

**Comment by hjonnala** [comment]
> Is this level of performance degradation on the Coral Micro expected? If so, why?

yes, it is expected.

![image](https://github.com/google-coral/coralmicro/assets/86132058/50e1acc2-aff4-4486-8757-23ff5ecf15f1)

![image](https://github.com/google-coral/coralmicro/assets/86132058/b4302ac8-8cc2-413d-9939-4e142fd88715)

**Comment by drummerhul** [comment]
To clarify, both performance measurements were running on the Edge TPU, not the MCU or CPU. The above discussion is a generic explanation of why models run slower on MCUs vs CPUs. But in our case, both models are accelerated by the Edge TPU. 

On the Coral Micro here is the code used to setup the Edge TPU Context: 
``` c++
 auto tpu_context = EdgeTpuManager::GetSingleton()->OpenDevice();
  if (!tpu_context) 
  {
    printf("ERROR: Failed to get EdgeTpu context\r\n");
    vTaskSuspend(nullptr);
  }
```

For reference, I did test the [CPU equivalent](https://raw.githubusercontent.com/google-coral/test_data/master/tf2_ssd_mobilenet_v2_coco17_ptq.tflite) on the RT 1176 (M7), Here is a sampling of the results:
``` 
Inference time : 11460 ms 
Inference time : 11458 ms 
Inference time : 11458 ms 
Inference time : 11459 ms 
Inference time : 11458 ms 
Inference time : 11457 ms 
Inference time : 11461 ms 
```
I would appreciate some help understanding why the accelerator performance is so much worse on the Coral Micro vs an RPI4 with a USB Accelerator Stick. Also, why does the benchmark for this model say `7.6ms` when we get `83ms` for the same model?
![image](https://github.com/google-coral/coralmicro/assets/10715200/4be25c25-5fdb-42e0-915b-ef891875eec2)

Thanks for your help.

**Comment by hjonnala** [comment]
![image](https://github.com/google-coral/coralmicro/assets/86132058/a69f82b4-207b-4bce-8892-27453fdfac4d)

In the above model only edgetpu-custom-op would run on TPU. Dequantize and Tflite_Detection_post_process ops would on CPU. 


> why does the benchmark for this model say `7.6ms` when we get `83ms` for the same model?


The differnce is due to change in host machines( Desktop CPU vs RPI4 CPU). Hope this helps..Thanks!!

**Comment by drummerhul** [comment]
I see. If we put a compiled model into netron, the only layer running on the Edge TPU is the 'edgetpu-custom-op`. Is that correct? 

Also, I tried to profile the execution time of the model using the `tflite:MicroProfiler` class and then ran the `Log()` method inside the class to see the layer's execution time. Unfortunately, all of the ms measurements come out to 0. Here is a portion of the console output:

```bash
edgetpu-custom-op took lu ticks (0 ms).
DEQUANTIZE took lu ticks (0 ms).
DEQUANTIZE took lu ticks (0 ms).
TFLite_Detection_PostProcess took lu ticks (0 ms).
``` 

Looking at the `coralmicro/third_party/tflite-micro/tensorflow/lite/micro/micro_time.cc` file it appears `TF_LITE_USE_CTIME` needs to be defined. So I added this line to the `CMakeLists.txt` in the base directory of the cloned out of tree repo. 

```
add_definitions(-DTF_LITE_USE_CTIME)
```
I'm getting the same result. 

How can we get `tflite::MicroProfiler` class to correctly output execution times?

Also, how do we profile the layers embedded within `edgetpu-custom-op` while executing on the Edge TPU?

Thanks!

**Comment by hjonnala** [comment]
> Also, how do we profile the layers embedded within `edgetpu-custom-op` while executing on the Edge TPU?

Its not possible to profile the layers embedded with edgetpu-cusstom-op.

> How can we get `tflite::MicroProfiler` class to correctly output execution times?

Please check with [tflite-micro](https://github.com/tensorflow/tflite-micro) team on how to profile a tflite model. Thanks!!
